apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary 
    app: myapp         
spec:
  containers: # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "500m" 
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "500Mi"