apiVersion: v1
kind: Namespace
metadata: 
  name: dev3
---  
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: dev3
spec:
  limits:
    - default:
        cpu: "500m"  # If not specified default limit is 1 vCPU per container     
        memory: "512Mi" # If not specified the Container's memory limit is set to 512Mi, which is the default memory limit for the namespace.
      defaultRequest:
        cpu: "300m" # If not specified default it will take from whatever specified in limits.default.cpu      
        memory: "256Mi" # If not specified default it will take from whatever specified in limits.default.memory
      type: Container 

----

apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: myapp-pod
  namespace: dev3
  labels: # Dictionary 
    app: myapp         
spec:
  containers: # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "500m" 
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "500Mi"