apiVersion: v1
kind: Namespace
metadata: 
  name: dev3
---  
                     
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: dev3
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi  
    pods: "2"    
    configmaps: "5" 
    persistentvolumeclaims: "5" 
    secrets: "5" 
    services: "5"

---

apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: myapp-pod3
  labels: # Dictionary 
    app: myapp-3        
spec:
  containers: # List
    - name: myapp-3
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "500m" 
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "500Mi"